"""empty message

Revision ID: 7862c20ae70b
Revises: 1c4707c41306
Create Date: 2019-08-10 06:37:39.359986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7862c20ae70b'
down_revision = '1c4707c41306'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('happy_meme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('happy_meme')
    # ### end Alembic commands ###
