"""empty message

Revision ID: e722e0eeac18
Revises: 7862c20ae70b
Create Date: 2019-08-10 16:11:53.764972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e722e0eeac18'
down_revision = '7862c20ae70b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_tag', sa.String(length=20), nullable=True),
    sa.Column('happy', sa.Integer(), nullable=True),
    sa.Column('sad', sa.Integer(), nullable=True),
    sa.Column('angry', sa.Integer(), nullable=True),
    sa.Column('shocked', sa.Integer(), nullable=True),
    sa.Column('thinking', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('news_tag')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stat')
    # ### end Alembic commands ###
